### ISSUE TITLE
Compile failed in macOS

### ISSUE THREAD

**Issue by ryancheung** [EmberEmu/Ember#12]
```
/Users/Ryan/EmberEmu/Ember/src/libs/spark/include/spark/ServicesMap.h:12:10: fatal error: 'spark/temp/ServiceTypes_generated.h' file not found
#include <spark/temp/ServiceTypes_generated.h>
```

@Chaosvex

**Comment by Chaosvex** [comment]
You need to compile FlatBuffers and use the compiler ('flatc') to generate those files by giving it the FBS files from "spark-schemas/".

For example:
flatc -c --scoped-enums "ServiceTypes.fbs" would produce ServiceTypes_generated.h.

I'm refactoring that part of the code at the moment (aiming to merge it in a few days but we'll see how it goes) so this will be done automatically when you build the project.

**Comment by ryancheung** [comment]
@Chaosvex Thanks!

**Comment by Nawuko** [comment]
@ryancheung You need to comment the "pragma warn" in Affinity.cpp out otherwise clang errors. Also when installing botan via brew you need to add --dev for the latest version "brew install botan --dev"

**Comment by ryancheung** [comment]
@Nawuko Thanks for notifying. I now get another error: 
```
/Users/Ryan/EmberEmu/Ember/src/login/LoginSession.cpp:34:25: error: no viable overloaded '='
        handler_.execute_async = [&](auto& action) {
```

macOS: 10.12
clang++ version: Apple LLVM version 8.0.0 (clang-800.0.38)

**Comment by ryancheung** [comment]
@Nawuko BTW, `brew install botan --dev` would install botan-1.10.13, but Ember requires at least version1.11.

So I have to manually download botan-1.11 and compile it.

**Comment by ryancheung** [comment]
It seems that using Linux for compiling would be much easier.

**Comment by Chaosvex** [comment]
There shouldn't be much difference between compiling it for Linux and Mac.

**Comment by ryancheung** [comment]
@Chaosvex Thanks, replacing it with std::shared_ptr<Action> works.

**Comment by ryancheung** [comment]
@Chaosvex Finally there're some errors in cmake's `INSTALL` commands:

```
Install the project...
-- Install configuration: ""
-- Up-to-date: /ember/login
CMake Error at src/login/cmake_install.cmake:57 (file):
  file INSTALL cannot find "/Users/Ryan/EmberEmu/Ember/configs/login".
Call Stack (most recent call first):
  src/cmake_install.cmake:32 (include)
  cmake_install.cmake:34 (include)
```

And I found this line 
```
INSTALL(DIRECTORY ${CMAKE_SOURCE_DIR}/configs/login/ DESTINATION ${CMAKE_INSTALL_PREFIX})
```
in many files, which is wrong since there's no configs/login directory in configs directory. There's only a `login.conf` file in it.

**Comment by Chaosvex** [comment]
Thanks. The install part isn't really used at the moment. I'll probably just remove it.

**Comment by Nawuko** [comment]
@ryancheung Maybe you have an old version installed. brew is installing botan 1.11 just fine. https://i.imgur.com/D17FB2P.png

**Comment by ryancheung** [comment]
@Nawuko I fount that command flag of latest brew to install development version of package is `--devel` not `--dev`.

**Comment by Nawuko** [comment]
Oh yea, my shell autocompletes args. So yea its --devel
