### ISSUE TITLE
`generate_client_proof` does not use leading zeros for `B` parameter (and possibly `A`)

### ISSUE THREAD

**Issue by username223** [EmberEmu/Ember#29]
Same as issue https://github.com/EmberEmu/Ember/issues/28 except it's a different parameter. This time I'm actually up to date. :)

Using the values of username: `A`, password: `A`, salt: `3C817155ED2215BF1623B08AE339977C294E590A39C8F64E9FEA0BB3131E7700`, b: `3ba2789f19be15cadadc2370d29abc0afae733e4691f1f0b0c6335b30ecfe306`, will lead to a public key B: `00334e88c85ab7ea8af9ed572bb216d2a731dbfb5c3a62a8222cb75ac83ed000` that replicates the issue.

Padding the array to 32 bytes fixes the issue for me on 1.12.1.
It might be (probably is) the same for A, although I can't manipulate the client to give me an A value with leading zeros.

**Comment by Chaosvex** [comment]
One of those issues I've fixed in the past but haven't addressed here. Should be fixed by e323d766a0d67686d15d89fe83d82377cf021906, thanks!
