### ISSUE TITLE
BigInt to vec conversion incorrectly removes leading big endian 0 byte for S key

### ISSUE THREAD

**Issue by username223** [EmberEmu/Ember#31]
The current way of converting the S key from a bigint to the value used for the interleaved hash fails on some occasions.
I believe that the error comes from the endianness conversion from bigint to a dynamic vector [here in `encode_flip`](https://github.com/EmberEmu/Ember/blob/368c9525fb0e550909fabe6ce6e39f029f8634df/src/libs/srp6/src/Server.cpp#L48) which then leaves the `hash` [here](https://github.com/EmberEmu/Ember/blob/368c9525fb0e550909fabe6ce6e39f029f8634df/src/libs/srp6/src/Util.cpp#L42) with a [leading big endian][trailing little endian] zero removed.

The fault was reproduced by connecting to the server until the server gave an incorrect proof for a known-correct username/password combination. The fault is relatively common, and appears somewhere between once every 100 or 200 times. It can reliably be reproduced just by continuously connecting.

All arrays are little endian and strings are big endian.

The issue can be isolated with the following values acquired from authentication with a 1.12.1 client:
```
S key before splitting (big endian): "00DBAC635E0DCCB91C5A38B6C2DA7F7685D2D5B0798298C6950A58B85BA07523"
S Key before splitting (little endian): [35, 117, 160, 91, 184, 88, 10, 149, 198, 152, 130, 121, 176, 213, 210, 133, 118, 127, 218, 194, 182, 56, 90, 28, 185, 204, 13, 94, 99, 172, 219, 0]
```
We do not know which S key the client ends up with, but we can deduce it by calculating the client proof which we know to be correct.

The correct client proof is
```
Correct client proof: [144, 246, 210, 216, 211, 95, 135, 31, 55, 208, 232, 221, 1, 6, 124, 251, 17, 35, 169, 180] 
```
While the incorrect client proof generated is
```
Wrong client proof: [4, 38, 71, 65, 60, 160, 68, 159, 49, 155, 248, 21, 78, 86, 26, 77, 233, 149, 103, 189]
```
The following values are also required for calculating the proof from the new S key:
```
username = "A"
password = "A"
Server PrivateKey: [125, 20, 230, 193, 202, 236, 177, 195, 241, 145, 219, 150, 25, 222, 202, 24, 37, 57, 85, 29, 134, 202, 200, 77, 144, 247, 93, 121, 152, 205, 229, 67]
Server PublicKey: [50, 152, 119, 101, 148, 100, 7, 182, 75, 215, 93, 67, 157, 44, 189, 68, 86, 99, 225, 227, 214, 238, 191, 133, 239, 234, 221, 52, 114, 121, 128, 56]
Client PublicKey: [145, 132, 93, 59, 255, 142, 18, 191, 100, 221, 218, 235, 60, 179, 186, 108, 100, 173, 134, 135, 52, 90, 101, 9, 95, 228, 63, 252, 252, 46, 90, 31]
Salt: [206, 208, 252, 32, 25, 77, 89, 249, 236, 80, 232, 50, 74, 86, 58, 117, 101, 83, 52, 20, 55, 227, 40, 174, 40, 103, 157, 70, 25, 218, 250, 38]
```

For my Rust implementation the following leads to identical behavior as Ember, and a highlighted fix:
```rust
pub fn to_equal_slice(&self) -> &[u8] {
	// 32 byte little endian array
	// We return a reference to avoid copying
    let mut s = &self.key[..];

	// This is the part that Ember does implicitly when
	// switching from BigInt to vector
	// Removing it fixes the issue
    if *s.last().unwrap() == 0 {
        s = &s[..s.len() - 1]
    }

	// Normal operation done by Ember in interleaved_hash
	// Quite possibly this should be a `while` instead
	// in case there are more zero pairs deeper in,
	// but I do not have the data to support this
    if *s.first().unwrap() == 0 {
        s = &s[1..];
    }
    if s.len() % 2 != 0 {
        s = &s[1..];
    }

    return s;
}
```

The following values are included for completeness:
```
Incorrect S Key: [117, 160, 91, 184, 88, 10, 149, 198, 152, 130, 121, 176, 213, 210, 133, 118, 127, 218, 194, 182, 56, 90, 28, 185, 204, 13, 94, 99, 172, 219], len: 30

Incorrect Session key: "6F1D481B40819CA537BF53DC20430B08A0E4912E0B47D5F70AE40A9F76D31ABBE75861D34EA8C177"
Incorrect SessionKey { key: [119, 193, 168, 78, 211, 97, 88, 231, 187, 26, 211, 118, 159, 10, 228, 10, 247, 213, 71, 11, 46, 145, 228, 160, 8, 11, 67, 32, 220, 83, 191, 55, 165, 156, 129, 64, 27, 72, 29, 111] }

Password verifier: [
        136, 48, 171, 245, 199, 21, 32, 98, 20, 183, 234, 9, 180, 214, 10, 57, 53, 164, 187, 5, 99,
        27, 152, 218, 5, 140, 194, 191, 254, 195, 182, 26,
    ];

```

**Comment by Chaosvex** [comment]
Thanks for this, I'll take a look.

**Comment by Chaosvex** [comment]
Patched this and added a regression test, although I believe it's a problem I've patched previously.

I think this is one of those quirks of the client and I'm not necessarily sure that it's doing the right thing, particularly since the padding of S, as the client does, isn't mentioned anywhere in the RFC that I can see. However, it works, so it'll do for now. Leaving this open for any additional comments.
