### ISSUE TITLE
SRP Client incorrectly calculates session key because of leading zeros

### ISSUE THREAD

**Issue by username223** [EmberEmu/Ember#33]
When converting the S key to the `interleaved_hash`, the client implementation does not pad with zeros, leading to an incorrect session key.

This issue has similarly been reported for [the server](https://github.com/EmberEmu/Ember/issues/31) and [fixed](https://github.com/EmberEmu/Ember/commit/6c3855d04e3343620dd4185a532894a144a3fd32), but [the client](https://github.com/EmberEmu/Ember/blob/0ed0a2456f6054b1bf8c6b7d2aa198c4be55e909/src/libs/srp6/src/Client.cpp#L62) still does it incorrectly.

Changing `encode_flip` to `encode_flip_1363` fixes this for me.

**Comment by Chaosvex** [comment]
Thanks, should be fixed!
