### ISSUE TITLE
Hello there!

### ISSUE THREAD

**Issue by ryancheung** [EmberEmu/Ember#6]
I found you in cmangos pull request. Then I found this project made by you and I think this is really interesting for me. The old mangos/cmangos is too old,  and someone need a complete rewrite for it by using the most modern and polished tools.

I like the project aims you listed. I'm currently a web developer and going to do some system programming using C++. I'm also a WoW lover or nostalgia. 

So I'm looking forward to join you within this project. 😃 

@Chaosvex

**Comment by Chaosvex** [comment]
I'll be making a fair few structural changes over the next couple of weeks to make life easier for contributors (such as merging the spark-new branch back into development and development back into master, along with updating the continuous integration for it), so I can't promise a smooth ride if you decide to compile it as it stands, although it shouldn't be _that_ bad.

Having said that, if you have any questions, feel free to ask and I'll do what I can to be of use. =)
